bluetti:
  server:
    sso: 'https://local-sso.poweroak.ltd:18443'
    gateway: 'https://local-gw.poweroak.ltd:18443'
    wss: 'ws://local-gw.poweroak.ltd:18888/api/edgeiotgw/ws-coordination/websocket'