bluetti:
  server:
    sso: 'http://dev-sso.poweroak.ltd:18888'
    gateway: 'http://dev-gw.poweroak.ltd:18888'
    client-id: 'HomeAssistant'
    client-secret: 'SG9tZUFzc2lzdGFudA=='
    wss: 'ws://dev-gw.poweroak.ltd:18888/api/edgeiotgw/ws-coordination/'